version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # ✅ ใช้แค่ตัวแปรนี้เพื่อตั้งรหัส root
      MYSQL_DATABASE: taskmanagement
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task_network

  prisma:
    image: node:latest
    container_name: prisma_migration
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "npm install && npx prisma migrate deploy && npm run dev"
    environment:
      DATABASE_URL: mysql://root:123456@mysql:3306/taskmanagement
    depends_on:
      - mysql
    networks:
      - task_network


networks:
  task_network:
    driver: bridge

volumes:
  mysql_data:
